apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-delta
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/tchaturvedi/deploy-platform-state.git
    targetRevision: mainline
    path: tenants/delta
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
