apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-gamma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tchaturvedi/deploy-platform-state.git
    targetRevision: mainline
    path: tenants/gamma
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
